### ISSUE TITLE
NacosConfigurationProperties does not support prefix

### ISSUE THREAD

**Issue by tiyilon** [nacos-group/nacos-spring-project#106]
springboot  annotation ConfigurationProperties  supports prefix .
but NacosConfigurationProperties  does not .

will NacosConfigurationProperties  support prefix propertie one day ?

**Comment by chuntaojun** [comment]
To support

**Comment by chuntaojun** [comment]
wait nacos-client 1.0.2

**Comment by chuntaojun** [comment]
# #118
