### ISSUE TITLE
使用xml启动，spring 5.1.3.RELEASE 报错

### ISSUE THREAD

**Issue by chenshun00** [nacos-group/nacos-spring-project#108]
严重: Exception sending context initialized event to listener instance of class org.springframework.web.context.ContextLoaderListener

org.springframework.beans.factory.BeanDefinitionStoreException: Unexpected exception parsing XML document from URL [file:/Users/chenshun/test/war/target/classes/aa.xml]; nested exception is java.lang.NoSuchMethodError: org.springframework.beans.factory.xml.BeanDefinitionParserDelegate.getEnvironment()Lorg/springframework/core/env/Environment;

没有这个方法了，看了一下低版本的 3.2.4还是有的

**Comment by chuntaojun** [comment]
ok, I'll fix it

**Comment by chuntaojun** [comment]
能够给下nacos-spring具体是哪个类报错吗

**Comment by chenshun00** [comment]
GlobalNacosPropertiesBeanDefinitionParser
NacosAnnotationDrivenBeanDefinitionParser

**Comment by chuntaojun** [comment]
already fix in version 0.2.3-RC1 #81
