### ISSUE TITLE
@ NacosConfigListener problem

### ISSUE THREAD

**Issue by nkorange** [nacos-group/nacos-spring-project#145]
See https://github.com/alibaba/nacos/issues/1563

**Comment by lirun970405606** [comment]
我遇到了类似的问题：

**Comment by lirun970405606** [comment]
我遇到了类似的问题：
@NacosConfigListener 与@NacosConfigurationProperties同时使用时，
@NacosConfigurationProperties先与服务端建立长轮询，此时@NacosConfigListener还没有addListener,会延迟30s之后才能加载配置

**Comment by wxr524720** [comment]
我用的0.3.3版本，@NacosConfigListener 项目启动的时候不会运行进来。但是只要nacos admin里修改了配置就会进来

**Comment by chuntaojun** [comment]
> 我用的0.3.3版本，@NacosConfigListener 项目启动的时候不会运行进来。但是只要nacos admin里修改了配置就会进来

你看下你的是不是这个问题：https://github.com/alibaba/nacos/issues/2004

**Comment by yongnny** [comment]
> 我遇到了类似的问题：
> @NacosConfigListener 与@NacosConfigurationProperties同时使用时，
> @NacosConfigurationProperties先与服务端建立长轮询，此时@NacosConfigListener还没有addListener,会延迟30s之后才能加载配置

我和你遇到了类似的问题，我这样解决了：我用的配置文件类型是 YML，然后我在所有 相关的注解中显式地 加入 type = ConfigType.YAML，貌似就解决了
