### ISSUE TITLE
@EnableNacos @NacosProperties can read from the properties file?

### ISSUE THREAD

**Issue by chuntaojun** [nacos-group/nacos-spring-project#151]
## Issue Description

Type: *bug report* or *feature request*

### Describe what happened (or what feature you want)

https://github.com/nacos-group/nacos-spring-boot-project/issues/86

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3.

**Comment by chuntaojun** [comment]
https://github.com/nacos-group/nacos-spring-project/issues/152

**Comment by chuntaojun** [comment]
这个是支持的，请看源码[NacosConfigBeanDefinitionRegistrar.java](https://github.com/nacos-group/nacos-spring-project/blob/master/nacos-spring-context/src/main/java/com/alibaba/nacos/spring/context/annotation/config/NacosConfigBeanDefinitionRegistrar.java)

**Comment by coderDylan** [comment]
> 这个是支持的，请看源码[NacosConfigBeanDefinitionRegistrar.java](https://github.com/nacos-group/nacos-spring-project/blob/master/nacos-spring-context/src/main/java/com/alibaba/nacos/spring/context/annotation/config/NacosConfigBeanDefinitionRegistrar.java)

这个我昨晚粗略的看了下代码并debug了几遍，以serverAddr属性为例，通过-D参数或者ServerListener的地方设置系统属性（system properties）是可以正常替换并获取到属性值的。但是，通过application.properties配置文件的定义方式是无法替换占位符的，最终看到的serverAddr的属性值始终都还是${xxx}。
NacosConfigBeanDefinitionRegistrar中的Environment属性会作为registerGlobalNacosProperties方法的PropertyResolve类型参数传递进去，实际执行PropertiesPlaceholderResolver对象的resolve动作的时候，会借助其propertyResolver属性（真实的实现类是PropertySourcesPropertyResolver）PropertySourcesPropertyResolver的getProperty方法中遍历PropertySources顺序查找，PropertySources只包含servletConfigInitParam、servletContextInitParam、jndi properties、system properties、system env等5种，所以根据key找不到自定义配置文件中的属性

**Comment by coderDylan** [comment]
![debug](https://user-images.githubusercontent.com/15723098/65166015-770d5480-da72-11e9-8e7e-02881188ec68.jpeg)

**Comment by coderDylan** [comment]
可以在自定义的ServletContextListener中去读取配置文件，让后提前将system properties 给set进去，变相的实现了这个需求。但是我意外发现，替换成spring 3.2.5之后是有问题的，NacosConfigBeanDefinitionRegistrar类虽然继承了EnvironmentAware接口，但是这个重写的setEnvironment方法压根不会被执行

**Comment by afeng395** [comment]
我用的也是spring 3.2.18版本。依旧也是如上的问题。environment里只有servletConfigInitParam、servletContextInitParam、jndi properties、system properties、system env5种。尝试了各种办法，最终都绕不开这个environment，替换不了占位符（其实就是在这个5个系统配置里找不到占位符对应的值）。最终自定义servletContextListener变相解决了该问题。部分代码如下（思路就是自己读取properties塞入system properites）
`public class NacosPropertiesServletContextListener implements ServletContextListener {

    //当有事件触发时，获取系统配置文件，塞入system properties
    @Override
    public void contextInitialized(ServletContextEvent sce) {

        Properties properties = System.getProperties();
        properties.setProperty("nacos.discovery.server-addr",AppPropertiesUtil.getProperty("nacos.discovery.server-addr"));
        properties.setProperty("nacos.discovery.namespace",AppPropertiesUtil.getProperty("nacos.discovery.namespace"));

    }`
