### ISSUE TITLE
友情提示，nacos-spring-context仅支持spring 3.2.18及以上版本

### ISSUE THREAD

**Issue by coderDylan** [nacos-group/nacos-spring-project#153]
`@Import(NacosConfigBeanDefinitionRegistrar.class)`
在NacosConfigBeanDefinitionRegistrar中实现了EnvironmentAware接口，需要调用setEnvironment方法获取到spring 抽象的环境信息。这个在nacos-spring-context项目官方提供的例子中是OK的，例子中使用的是3.2.18版本。
但是，在我们旧项目使用的spring 3.2.5版本（由于种种原因不能轻易升级spring版本），在debug过程中发现setEnvironment方法不会被调用的，所以会导致registerBeanDefinitions方法往下执行会最终引发NPE...
通过debug和对比spring 3.2.5和spring3.2.18的源代码，发现了一些差异和造成该问题的原因

![3 2 5](https://user-images.githubusercontent.com/15723098/65336507-13f9fa00-dbf9-11e9-8e46-03f9d1510d76.jpeg)
![Uploading 3.2.18.jpeg…]()

**Comment by coderDylan** [comment]
![3 2 18](https://user-images.githubusercontent.com/15723098/65336854-aac6b680-dbf9-11e9-9179-c3f262afc309.jpeg)

**Comment by chuntaojun** [comment]
Thank you for your care

**Comment by coderDylan** [comment]
```
 @Override
    public void setBeanFactory(BeanFactory beanFactory) throws BeansException {
        this.beanFactory = beanFactory;
        //fix spring3.2.5 bug(该版本不会invoke setEnvironment方法，会导致environment属性为null，registerBeanDefinitions方法最终执行会发生NPE)
        this.environment = beanFactory.getBean(Environment.class);
    }
```
setBeanFactory方法是正常被invoke的，所以可以这样变现的解决environment属性为null的问题。

不过spring 3.2.5下面还会有其他的问题，由于依赖了alibaba的spring-context-support包，
该包下的AnnotationInjectedBeanPostProcessor#findInjectionMetadata方法中会执行InjectionMetadata#needsRefresh方法会产生NoSuchMethodError，
在spring 3.2.5中InjectionMetadata根本没有needsRefresh方法

**Comment by mercyblitz** [comment]
Great Job~ You'd better update Spring framework to 4.0 and above~

**Comment by SmileTower** [comment]
spring-context-support version is old， dubbo 2.7.6 this version 1.0.6

**Comment by mercyblitz** [comment]
> version

Updated in the new version.
