### ISSUE TITLE
support @Value auto refresh

### ISSUE THREAD

**Issue by chuntaojun** [nacos-group/nacos-spring-project#160]
## Issue Description

Type: *bug report* or *feature request*

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3.

**Comment by mercyblitz** [comment]
Please revert this feature, it will make confuse on Spring stack

**Comment by chuntaojun** [comment]
Ok，This is a mistake in my personal thinking and I will withdraw it this week

发自我的iPhone

在 2019年12月3日，16:39，Mercy Ma <notifications@github.com> 写道：

﻿

Please revert this feature, it will make confuse on Spring stack

**Comment by chuntaojun** [comment]
这个特性会在下一个版本移除
