### ISSUE TITLE
[Question]Not match expect value when app startup

### ISSUE THREAD

**Issue by nkorange** [nacos-group/nacos-spring-project#168]
Refer to https://github.com/alibaba/nacos/issues/2037

**Comment by chuntaojun** [comment]
@NacosValue 注解的使用请详细看下，有一个autoRefresh熟悉

**Comment by hello-zhengzq** [comment]
> 
> 
> @NacosValue 注解的使用请详细看下，有一个autoRefresh熟悉

![图片](https://user-images.githubusercontent.com/51627771/68525673-e4b95c80-030e-11ea-81dc-90299fc51a09.png)
这个autorefresh是true和false都有设置，疑问是即使nacosserver那里有配置，服务启动的时候，NacosValue注解的变量都是默认值，并没有取到server配置的值，而server的值刷新后autorefresh为true的变量值会刷新，这个没问题

**Comment by chuntaojun** [comment]
你是用的nacos-spring-context v0.3.4，那不应该才对啊，启动时已经拉取下来了的

**Comment by hello-zhengzq** [comment]
> 
> 
> 你是用的nacos-spring-context v0.3.4，那不应该才对啊，启动时已经拉取下来了的

我发现我建了个干净的项目demo直接测试是ok的，在项目一样配置，就有这个问题QAQ，而已对象注入没问题，就nacosvalue这个注解注入就会这样

**Comment by lirun970405606** [comment]
> > 你是用的nacos-spring-context v0.3.4，那不应该才对啊，启动时已经拉取下来了的
> 
> 我发现我建了个干净的项目demo直接测试是ok的，在项目里一样的配置，就有这个问题QAQ，而且对象注入没问题，就nacosvalue这个注解注入就会这样

您在controller里面配置是从mvc子容器里面寻找的,确认一下是否已经注册了，或者尝试一下在Service层获取配置

**Comment by chuntaojun** [comment]
> > 你是用的nacos-spring-context v0.3.4，那不应该才对啊，启动时已经拉取下来了的
> 
> 我发现我建了个干净的项目demo直接测试是ok的，在项目里一样的配置，就有这个问题QAQ，而且对象注入没问题，就nacosvalue这个注解注入就会这样

这不是一个bug，设计如此，监听器是监听本地配置文件与远端配置文件的变更，只有实际发生变更才会触发，如果需要利用listener的能力，建议使用com.alibaba.nacos.api.config.ConfigService#getConfigAndSignListener，程序启动时get到配置文件，然后会注册listener。listener会去监听这之后的文件变动，完全依赖listener不太建议，nacos本身存在快照的概念。
