### ISSUE TITLE
配置了namespace，但实际不一致

### ISSUE THREAD

**Issue by chuntaojun** [nacos-group/nacos-spring-project#169]
## Issue Description

Type: *bug report*

### Describe what happened (or what feature you want)

see https://github.com/alibaba/nacos/issues/2055

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3.

**Comment by WywTed** [comment]
使用 dubbo 2.7.1 的时候也出现过这种情况， namespace 配置无效； 简单调试代码发现， 在实例化 NacosNamingService 的时候， 读不到 dubbo 的 parameter 参数，实例化完 NacosNamingService 后在加载 dubbo 相关配置时又能读到 dubbo.registry.parameters 相关参数，但这时 nacos 注册的 namespace 肯定是默认的 ‘public’ 了，这个时候应该是 来加载相关的了，但这种情况并不是一定发生，不知道是不是和相关的依赖也有关系，觉得需要 将 依赖信息也一并贴上来 @jqsl2012 （ps: 如果要临时解决这个，可以在 环境变量中加上 ‘namespace=xx’ 的配置， 因为 nacos-client 端源码会解析环境变量 ‘namespace’）

**Comment by chuntaojun** [comment]
> 使用 dubbo 2.7.1 的时候也出现过这种情况， namespace 配置无效； 简单调试代码发现， 在实例化 NacosNamingService 的时候， 读不到 dubbo 的 parameter 参数，实例化完 NacosNamingService 后在加载 dubbo 相关配置时又能读到 dubbo.registry.parameters 相关参数，但这时 nacos 注册的 namespace 肯定是默认的 ‘public’ 了，这个时候应该是 来加载相关的了，但这种情况并不是一定发生，不知道是不是和相关的依赖也有关系，觉得需要 将 依赖信息也一并贴上来 @jqsl2012 （ps: 如果要临时解决这个，可以在 环境变量中加上 ‘namespace=xx’ 的配置， 因为 nacos-client 端源码会解析环境变量 ‘namespace’）

你用的也是nacos-spring-project的吗

**Comment by WywTed** [comment]
不是的， springboot

**Comment by jqsl2012** [comment]
@chuntaojun 

我是参考官网的例子 https://nacos.io/zh-cn/docs/use-nacos-with-dubbo.html

provider指定namespace是dev的id
<nacos:global-properties server-addr="nacos://localhost:8848"
                             namespace="2fa2ea31-d52d-4b18-aff4-824a15218502"/>

consumer指定namespace并不存在。无论namespace怎样指定都能访问到provider，但我期望是访问不到。
<nacos:global-properties server-addr="localhost:8848" namespace="123" />
System.setProperty("nacos.config.namespace", "111");


![image](https://user-images.githubusercontent.com/6802595/68915236-12cdef00-079c-11ea-8549-2bd5c33f103d.png)

![image](https://user-images.githubusercontent.com/6802595/68915275-37c26200-079c-11ea-9459-773a72897c7f.png)

**Comment by jqsl2012** [comment]
![image](https://user-images.githubusercontent.com/6802595/68915392-d9e24a00-079c-11ea-9989-30cec04f67f4.png)

**Comment by chuntaojun** [comment]
这个dubbo的访问namespace信息你要配置在dubbo的registry-address里面
