### ISSUE TITLE
基于springboot2.2.0 和springboot-admin集成时，连接不上springboot-admin

### ISSUE THREAD

**Issue by cui-stack** [nacos-group/nacos-spring-project#175]
基于springboot2.2.0 和springboot-admin集成时，连接不上springboot-admin，配置没有生效

**Comment by chuntaojun** [comment]
请先排查springboot2.2.0 和springboot-admin是否版本兼容，移除nacos依赖是否可以连上

**Comment by cui-stack** [comment]
感谢！！
目前项目基于springboot2.2，dubbo2.6.0，springboot-admin2.2.0，nacos0.2.3，mysql，rabbitmq，项目部署在docker
使用本地配置（properties，yml）
结果： 项目正常
使用naco配置properties
结果：除springboot-admin，其他正常
使用naco配置yml，配置nacos.config.type=yaml
结果：项目不能启动

**Comment by chuntaojun** [comment]
试一试配置预加载

发自我的iPhone

在 2019年12月18日，11:34，cui <notifications@github.com> 写道：

﻿

感谢！！
目前项目基于springboot2.2，dubbo2.6.0，springboot-admin2.2.0，nacos0.2.3，mysql，rabbitmq，项目部署在docker
使用本地配置（properties，yml）
结果： 项目正常
使用naco配置properties
结果：除springboot-admin，其他正常
使用naco配置yml，配置nacos.config.type=yaml
结果：项目不能启动

**Comment by cui-stack** [comment]
使用nacos.config.enable-remote-sync-config=true 没有效果，另外nacos的springboot的sample是跑多环境的配置吗，好像跑不起来LOL

**Comment by cui-stack** [comment]
也可能是我架构原因把，不行就算了把
