### ISSUE TITLE
nacos集成spring不能实现配置文件的热更新

### ISSUE THREAD

**Issue by lizhibo0914** [nacos-group/nacos-spring-project#176]
Spring+springMVC的项目集成nacos, 不能实现热更新配置文件, 修改文件之后必须重启配置文件才能生效, 怎么能实现热更新呢?

**Comment by chuntaojun** [comment]
贴下你的配置，我这里测试ok的，或者看下置顶的issue

发自我的iPhone

在 2019年12月19日，16:45，lizhibo0914 <notifications@github.com> 写道：

﻿

Spring+springMVC的项目集成nacos, 不能实现热更新配置文件, 修改文件之后必须重启配置文件才能生效, 怎么能实现热更新呢?

**Comment by lizhibo0914** [comment]
<nacos:annotation-driven></nacos:annotation-driven>
    
    <nacos:global-properties server-addr="localhost:8848"/>
    
    <nacos:property-source data-id="application-dev.properties" auto-refreshed="true"/>

![image](https://user-images.githubusercontent.com/27732536/71168188-1f5cd000-2291-11ea-83cc-d91c517905f4.png)

**Comment by mercyblitz** [comment]
这个并不是属于 Nacos 的实现范畴。实际上配置文件静态化之后，比如 Docker 化，没有办法实现热更新，Spring Framework 没有提供这样的机制~
