### ISSUE TITLE
使用环境变量，macos，linux不支持key中有.，希望支持.修改为_

### ISSUE THREAD

**Issue by jin82** [nacos-group/nacos-spring-project#178]
## Issue Description

bug report

### Describe what happened (or what feature you want)

比如： export nacos.namespace=1
====>-bash: export: `nacos.namespace=1': 不是有效的标识符
希望可以支持 nacos_namespace=1这种配置

**Comment by chuntaojun** [comment]
You can configure these parameters as long as they are loaded into the environment by spring

@NacosProperties(serverAddr = "${server_addr}")，and system env  server_addr=ip:port
