### ISSUE TITLE
spring+spring MVC不能进行自动热更新

### ISSUE THREAD

**Issue by nkorange** [nacos-group/nacos-spring-project#180]
Refer to https://github.com/alibaba/nacos/issues/2202

**Comment by rushsky518** [comment]
非注解方式时，当远程配置文件改变后， environment 中的配置没有变化

**Comment by chuntaojun** [comment]
> 非注解方式时，当远程配置文件改变后， environment 中的配置没有变化

看下listener是否有接收到nacos的推送，有可能是因为Spring Context的关系导致的

**Comment by chuntaojun** [comment]
该问题已修复，由于xml配置解析没有解析相应的而外信息项导致的

**Comment by jungleyoung** [comment]
我使用nacos-spring-context 1.1.1 也遇到相同的问题，需要如何解决呢？
使用配置类配置时可以实现配置热更新但是使用xml配置就不行了。
配置类：
`@Profile(value = {"dev","default"})
@Configuration
@EnableNacosConfig(globalProperties = @NacosProperties(serverAddr = "127.0.0.1:8848", username="read",password="read",namespace = "41635d4a-1a7f-4315-a6ae-5a9056ccac75"))
@NacosPropertySource(dataId = "dev-nacos.properties", groupId = "DEFAULT_GROUP", autoRefreshed = true, properties = @NacosProperties())
public class NacosConfDev {
}`
xml:


    <nacos:annotation-driven/>
    <nacos:global-properties server-addr="127.0.0.1:8848" namespace="41635d4a-1a7f-4315-a6ae-5a9056ccac75" username="read" password="read"/>
    <nacos:property-source data-id="dev-nacos.properties" group-id="DEFAULT_GROUP" auto-refreshed="true"  />
</beans>
