### ISSUE TITLE
使@NacosPropertySource注解的groupId属性使用placeholder占位符时，不支持默认值

### ISSUE THREAD

**Issue by robin977** [nacos-group/nacos-spring-project#185]
场景:
@configuration
@EnableNacosConfig(globalProperties = @NacosProperties(serverAddr ="${nacos.addr:localhost}"))
@NacosPropertySources({
@NacosPropertySource(dataId = “datasource”, autoRefreshed = true,
groupId = "${nacos.group:DEFAULT_GROUP}")
public class NacosConfiguration { }
解析@NacosPropertySource属性值在AbstractNacosPropertySourceBuilder的doBind方法，
groupId = NacosUtils.readFromEnvironment(groupId, environment);
在读取属性时，只是简单的去掉group上的${}，没有将默认值分开

**Comment by chuntaojun** [comment]
我这里能正常识别默认值，你的版本是多少？
