### ISSUE TITLE
springboot nacos 如何用@NacosConfigListener监听yml配置的变化

### ISSUE THREAD

**Issue by chenjianshuo** [nacos-group/nacos-spring-project#189]
Describe what happened (or what feature you want)
nacos配置：

 alarm:     <br/>
    weixin:    <br/>
         api: http://172.25.63.72:8080/weixin    <br/>

获取动态配置如下

@(dataId = "spring-nacos-demo.yml",type = ConfigType.YAML)
public void onRecive(Properties value){
System.out.println("Properties："+ value);
}
打印：Properties：{weixin=, api=http://172.25.63.72:8080/weix, alarm=}

@NacosConfigListener(dataId = "spring-nacos-demo.yml",type = ConfigType.YAML)
public void onRecive(String value){
    System.out.println("String："+ value);
}
打印：String：alarm:
weixin:
api: http://172.25.63.72:8080/weix

Describe what you expected to happen
如何获取：alarm.weixin.api的值呢

How to reproduce it (as minimally and precisely as possible)
**Tell us your environment**

com.alibaba.boot nacos-config-spring-boot-starter 0.2.4

Anything else we need to know?

**Comment by chuntaojun** [comment]
This will be added in the next version and will automatically become a Map object when the parameter is Map
