### ISSUE TITLE
使@NacosPropertySource注解时，如果namesapce属性使用placeholder占位符时，无法解析

### ISSUE THREAD

**Issue by 18207556302** [nacos-group/nacos-spring-project#191]
我配置文件中server-addr和groupId使用站位符，可以解析到，但是namesapce属性没有支持。
nacos.config.namespace=${nacos.namespace}
nacos.config.data-id=${nacos.config.data.id}
nacos.config.group=${group.name}
查下nacos-spring-project的NacosPropertySource.java发现里面没有namespace的属性，故该属性无法使用占位符

**Comment by chuntaojun** [comment]
我这里该项目并不会出现此问题，是否是springboot项目
