### ISSUE TITLE
namespace 配置

### ISSUE THREAD

**Issue by elizwy** [nacos-group/nacos-spring-project#204]
## 我使用的是nacos-spring-context，配置文件中配置namespace：nacos.config.namespace=f4c6b548-ae3e-445f-9677-2244fa9e24ed
发现读取得还是public 空间的，网上查一边，发现spring-boot,dubbo,cloud对改namespce的设置都不一样，我想知道spring 项目这个设置又是什么呢？

**Comment by mercyblitz** [comment]
`nacos.namespace=${...}`
