### ISSUE TITLE
NacosPropertiesBuilder类依赖lang3问题

### ISSUE THREAD

**Issue by liyanglin** [nacos-group/nacos-spring-project#256]
https://github.com/alibaba/nacos/issues/5409#issuecomment-822904186
### nacos-config-spring-boot-starter   ：autoconfigure中 NacosPropertiesBuilder 使用了lang3的StringUtils
![image](https://user-images.githubusercontent.com/33758785/115345049-cda7bb00-a1e0-11eb-8f97-e9ff0601ffd1.png)
但是在依赖的nacos-client中的api已经提供了StringUtils （method: isEmpty,isBlank）
![image](https://user-images.githubusercontent.com/33758785/115345792-dfd62900-a1e1-11eb-98ef-e3306cdbb000.png)
**作为一个starter使用时还需要添加lang3依赖，出于对依赖的简洁性考虑此处的
import org.apache.commons.lang3.StringUtils;
if(StringUtils.isNotEmpty(##))
是否可以改成
import com.alibaba.nacos.api.utils.StringUtils
if(！StringUtils.isEmpty(##))**
@KeRan213539

**Comment by KeRan213539** [comment]
com.alibaba.nacos.api.utils.StringUtils 计划将来要合并到 nacos-common 中,  而nacos-common中的工具类是提供给nacos自身使用的，随时会发生重构，移动，删除等操作，并非提供外部使用的api。虽然可以使用，但是容易造成版本间的兼容性问题。

**Comment by liyanglin** [comment]
> com.alibaba.nacos.api.utils.StringUtils 计划将来要合并到 nacos-common 中, 而nacos-common中的工具类是提供给nacos自身使用的，随时会发生重构，移动，删除等操作，并非提供外部使用的api。虽然可以使用，但是容易造成版本间的兼容性问题。

随着nacos api计划合并到common后，可以理解为 autoconfigure后面也将不依赖nacos api了吧

**Comment by KeRan213539** [comment]
> > com.alibaba.nacos.api.utils.StringUtils 计划将来要合并到 nacos-common 中, 而nacos-common中的工具类是提供给nacos自身使用的，随时会发生重构，移动，删除等操作，并非提供外部使用的api。虽然可以使用，但是容易造成版本间的兼容性问题。
> 
> 随着nacos api计划合并到common后，可以理解为 autoconfigure后面也将不依赖nacos api了吧

理论上来说, nacos的包只会依赖 nacos-client
