### ISSUE TITLE
服务端配置修改后，不支持@Value值的动态变更

### ISSUE THREAD

**Issue by wuhaoqiang1** [nacos-group/nacos-spring-project#285]
## 服务端配置修改后，不支持@Value值的动态变更

Type: feature request

### 希望作为配置中心可以做到服务端修改配置，@Value值的动态变更

作为动态配置中心，应更加关注到使用者业务，目前@NacosValue注解支持值动态变更，@Value值不支持，

1. @NacosValue注解的表达式解析较差，不支持如:123${key1}{key2}321等表达式，不如@Value
2. 耦合性太高，后续项目更改动态配置中心，所有使用@NacosValue的地方都需要更改

**Comment by mercyblitz** [comment]
@Value 不应该支持动态切换，可以将 @NacosValue 增强即可

**Comment by wuhaoqiang1** [comment]
> 

为什么@Value不应该支持，用@Value不是更贴近于Spring，降低耦合性，即使从其他动态配置中心迁移过来改动也更小

**Comment by VanillaIceCreams** [comment]
兄弟，这个issue的改动,新增的那个SpringValueAnnotationBeanPostProcessor有BUG啊，我properties配置文件里写了个“product.install.specification=”的配置，等于号后面没有填东西。 然后我代码里用   ` @Value("${product.install.specification:0}")
    private              Integer         installSpecification;`注入，代码里会解析出个null，然后往injectedObjectsCache里注入。ConcurrentHashMap又不支持value=null，直接空指针了

**Comment by wuhaoqiang1** [comment]
***@***.***也会出现一样的问题。
目前看到nacos-spring-context-2.1.1还处于预发版本，而且在springboot的版本nacos-spring-boot-project中也没有引入最新版本的nacos-spring-context，目前感觉不太稳定，如果要使用可以自己考虑过滤掉null值不缓存，比如：
if (injectedObject != null) {
    injectedObjectsCache.putIfAbsent(cacheKey, injectedObject);
}



或者可以考虑使用spring-cloud-starter-alibaba-nacos-config项目，这个比较稳定，但是在需要动态刷新的bean需要配合使用spring ***@***.***实现动态刷新




W
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "nacos-group/nacos-spring-project"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2025年5月28日(星期三) 晚上8:04
***@***.***&gt;;
***@***.***&gt;;"State ***@***.***&gt;;
主题:&nbsp;Re: [nacos-group/nacos-spring-project] ***@***.***值的动态变更 (Issue #285)



VanillaIceCreams left a comment (nacos-group/nacos-spring-project#285)
 
兄弟，这个issue的改动,新增的那个SpringValueAnnotationBeanPostProcessor有BUG啊，我properties配置文件里写了个“product.install.specification=”的配置，等于号后面没有填东西。 然后我代码里用    @Value("${product.install.specification:0}") private              Integer         installSpecification;注入，代码里会解析出个null，然后往injectedObjectsCache里注入。ConcurrentHashMap又不支持value=null，直接空指针了
