### ISSUE TITLE
使用spring cloud gateway配合nacos缓存问题

### ISSUE THREAD

**Issue by l42111996** [nacos-group/nacos-spring-project#288]
## Issue Description

Type: *bug report* or *feature request*

### Describe what happened (or what feature you want)

spring cloud gateway配合nacos 使用 loadbalancer的cache，这里会因为loadbalancer的ttl为35秒，后端服务下线后gateway还会把流量输出到对应的服务导致部分404

### Describe what you expected to happen

1，想了解正确做法是否应该禁用loadbalancer的cache功能？
2，nacos客户端是否有本地缓存？
3，有什么更好的解决方案吗？

### How to reproduce it (as minimally and precisely as possible)
1. 
2. 
3. 

### Anything else we need to know?

是否需要加上retry更好？每次从nacos客户端取的时候可能因为瞬间下线出现404，是否应该进行一次retry发到另外的服务

**Comment by hujun-w-2** [comment]
nacos的sdk本身的缓存数据会实时更新，是springcloud的loadbalancer强行加的缓存，这块可以自己实现一个loadbalancer解决
