### ISSUE TITLE
Support reading configuration in json format, not only properties

### ISSUE THREAD

**Issue by fangjian0423** [nacos-group/nacos-spring-project#77]

**Comment by chuntaojun** [comment]
已实现，json可以和yaml一起解析

**Comment by Gred01** [comment]
how does it work?

**Comment by chuntaojun** [comment]
> how does it work?

I will update nacos client version to v1.1.0 to enable this json configuration support

**Comment by Gred01** [comment]
> > how does it work?
> 
> I will update nacos client version to v1.1.0 to enable this json configuration support

可以仔细说下吗？能不能给个例子？

**Comment by chuntaojun** [comment]
> > > how does it work?
> > 
> > 
> > I will update nacos client version to v1.1.0 to enable this json configuration support
> 
> 可以仔细说下吗？能不能给个例子？

稍等下，我这里更新一个测试用例即可

**Comment by chuntaojun** [comment]
> how does it work?

你可以查看测试用例下的[NacosPropertySourceJsonTest](https://github.com/chuntaojun/nacos-spring-project/blob/develop/nacos-spring-context/src/test/java/com/alibaba/nacos/spring/context/annotation/config/NacosPropertySourceJsonTest.java)

**Comment by Gred01** [comment]
> > how does it work?
> 
> 你可以查看测试用例下的[NacosPropertySourceJsonTest](https://github.com/chuntaojun/nacos-spring-project/blob/develop/nacos-spring-context/src/test/java/com/alibaba/nacos/spring/context/annotation/config/NacosPropertySourceJsonTest.java)

OK，ths，我看下

**Comment by 3071776** [comment]
能不能直接通过@Value 将整个json注入到JSONObject 对象

**Comment by sadlay** [comment]
> 能不能直接通过@value 将整个json注入到JSONObject 对象

同问

**Comment by void1104** [comment]
> > how does it work?
> 
> 你可以查看测试用例下的[NacosPropertySourceJsonTest](https://github.com/chuntaojun/nacos-spring-project/blob/develop/nacos-spring-context/src/test/java/com/alibaba/nacos/spring/context/annotation/config/NacosPropertySourceJsonTest.java)

图中的链接已经失效了
