### ISSUE TITLE
nacosConfigHttpHandler handler should be initialized

### ISSUE THREAD

**Issue by atkawa7** [nacos-group/nacos-spring-project#78]
https://github.com/nacos-group/nacos-spring-project/blob/9500763e2c56a63ede03fadef8d5260f5fcf5793/nacos-spring-samples/nacos-embedded-webserver/src/main/java/com/alibaba/nacos/embedded/web/server/EmbeddedNacosHttpServer.java#L56

**Comment by mercyblitz** [comment]
Just the sample code
