### ISSUE TITLE
Reading dataId from environment 

### ISSUE THREAD

**Issue by yidadi** [nacos-group/nacos-spring-project#83]
we can Reading dataId from environment 

protected NacosPropertySource doBuild(String beanName, T beanDefinition, Map<String, Object> runtimeAttributes) {

        // Get annotation metadata
        String name = (String) runtimeAttributes.get(NAME_ATTRIBUTE_NAME);
        String dataId = (String) runtimeAttributes.get(DATA_ID_ATTRIBUTE_NAME);
        String groupId = (String) runtimeAttributes.get(GROUP_ID_ATTRIBUTE_NAME);
        Map<String, Object> nacosPropertiesAttributes = (Map<String, Object>) runtimeAttributes.get(PROPERTIES_ATTRIBUTE_NAME);
        final String realDataId = environment.getProperty(dataId,dataId);
        Properties nacosProperties = resolveProperties(nacosPropertiesAttributes, environment, globalNacosProperties);

        String nacosConfig = nacosConfigLoader.load(realDataId, groupId, nacosProperties);

        if (!StringUtils.hasText(nacosConfig)) {
            if (logger.isWarnEnabled()) {
                logger.warn(format("There is no content for NacosPropertySource from dataId[%s] , groupId[%s] , properties[%s].",
                        realDataId,
                        groupId,
                        valueOf(nacosPropertiesAttributes)));
            }
        }

        if (!StringUtils.hasText(name)) {
            name = buildDefaultPropertySourceName(realDataId, groupId, nacosProperties);
        }

        NacosPropertySource nacosPropertySource = new NacosPropertySource(name, nacosConfig);

        nacosPropertySource.setBeanName(beanName);

        String beanClassName = beanDefinition.getBeanClassName();
        if (StringUtils.hasText(beanClassName)) {
            nacosPropertySource.setBeanType(resolveClassName(beanClassName, classLoader));
        }
        nacosPropertySource.setGroupId(groupId);
        nacosPropertySource.setDataId(realDataId);
        nacosPropertySource.setProperties(nacosProperties);

        initNacosPropertySource(nacosPropertySource, beanDefinition, runtimeAttributes);

        return nacosPropertySource;

    }

**Comment by chuntaojun** [comment]
could you describe this problem details?

**Comment by yidadi** [comment]
Read the dataId from the environment variable.

**Comment by chuntaojun** [comment]
> Read the dataId from the environment variable.

like this ?
@NacosPropertySource(dataId= ${dataId})

**Comment by chuntaojun** [comment]
Will be added in the next version

**Comment by yidadi** [comment]
yes ,just like  this final String realDataId = environment.getProperty(dataId,dataId);
