### ISSUE TITLE
Can NacosProperties using properties in application.properties?

### ISSUE THREAD

**Issue by limng06** [nacos-group/nacos-spring-project#84]
Can NacosProperties using properties in application.properties?

I found NacosProperties placeHolder can user systemEnv and systemProperties, 
but i don't like to use params like this '-Dnacos.namespace=XXXX'
i'd like to know that if i can use property in 'application.properties' instead.

```java
@Configuration
@EnableNacosConfig(globalProperties = @NacosProperties(serverAddr = "${nacos.server-addr}", namespace = "${nacos.namespace}"))
@NacosPropertySources({
        @NacosPropertySource(dataId = "TEST"),
        @NacosPropertySource(dataId = "RABBIT_CONFIG", groupId = "MQ")
})
@Component
public class NacosConfig {
}
```

**Comment by mercyblitz** [comment]
It depends on the declaration order. If you annotate `@NacosPropertySource` in some configuraton class that is scanned by `@ComponentScan`, it could use `application.properties`.
