### ISSUE TITLE
Spring boot 项目启动时 偶发NPE 概率很高 平均概率 50% 

### ISSUE THREAD

**Issue by Logicf** [nacos-group/nacos-spring-project#85]
Spring boot 2.1.1-release
具体Nacos 依赖
 <dependency>
            <groupId>com.alibaba.nacos</groupId>
            <artifactId>nacos-api</artifactId>
<version>1.0.0</version>
        </dependency>
        <dependency>
            <groupId>com.alibaba.nacos</groupId>
            <artifactId>nacos-client</artifactId>
<version>1.0.0</version>
        </dependency>
        <dependency>
            <groupId>com.alibaba.boot</groupId>
            <artifactId>nacos-config-spring-boot-starter</artifactId>
            <exclusions>
                <exclusion>
                    <groupId>com.alibaba.nacos</groupId>
                    <artifactId>nacos-api</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>com.alibaba.nacos</groupId>
                    <artifactId>nacos-client</artifactId>
                </exclusion>
            </exclusions>

        </dependency>
        <dependency>
            <groupId>com.alibaba.boot</groupId>
            <artifactId>nacos-discovery-spring-boot-starter</artifactId>
<version>0.2.1</version>
            <exclusions>
                <exclusion>
                    <groupId>com.alibaba.nacos</groupId>
                    <artifactId>nacos-api</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>com.alibaba.nacos</groupId>
                    <artifactId>nacos-client</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>com.alibaba.boot</groupId>
            <artifactId>nacos-config-spring-boot-actuator</artifactId>
<version>0.2.1</version>
            <exclusions>
                <exclusion>
                    <groupId>com.alibaba.nacos</groupId>
                    <artifactId>nacos-api</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>com.alibaba.nacos</groupId>
                    <artifactId>nacos-client</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
这个问题在手动引入 nacos-client 1.0.0 之前就已经存在

![image](https://user-images.githubusercontent.com/23493090/56478744-176f4500-64e4-11e9-91e0-558460304aca.png)

**Comment by nkorange** [comment]
@Logicf 下周修复

**Comment by yjwfn** [comment]
> @Logicf 下周修复

这个问题在修复么， 现在出现的机率非常高，影响使用。

**Comment by chuntaojun** [comment]
> > @Logicf 下周修复
> 
> 这个问题在修复么， 现在出现的机率非常高，影响使用。

方便告知下application.properties有关nacos是如何配置的吗

**Comment by yjwfn** [comment]
# Nacos discovery
nacos.discovery.server-addr=gm.xxx.top:17448
nacos.discovery.namespace=3697a1c2-3bd2-4802-bbab-50ddaf3eaa6f

# Nacos config
nacos.config.serverAddr=gm.xxx.top:17448
nacos.config.enabled=true
nacos.config.namespace=3697a1c2-3bd2-4802-bbab-50ddaf3eaa6f

**Comment by chuntaojun** [comment]
> # Nacos discovery
> nacos.discovery.server-addr=gm.xxx.top:17448
> nacos.discovery.namespace=3697a1c2-3bd2-4802-bbab-50ddaf3eaa6f
> 
> # Nacos config
> nacos.config.serverAddr=gm.xxx.top:17448
> nacos.config.enabled=true
> nacos.config.namespace=3697a1c2-3bd2-4802-bbab-50ddaf3eaa6f
> 
> > > > @Logicf 下周修复
> > > 
> > > 
> > > 这个问题在修复么， 现在出现的机率非常高，影响使用。
> > 
> > 
> > 方便告知下application.properties有关nacos是如何配置的吗

目前我这里没有复现出错误，所以能不能麻烦你在出现此问题时，调试到com.alibaba.nacos.spring.context.event下的DeferredApplicationEventPublisher对象，查看List<ApplicationEvent> deferredEvents列表中的内容并截图下？

**Comment by yjwfn** [comment]
> > # Nacos discovery
> > nacos.discovery.server-addr=gm.xxx.top:17448
> > nacos.discovery.namespace=3697a1c2-3bd2-4802-bbab-50ddaf3eaa6f
> > # Nacos config
> > nacos.config.serverAddr=gm.xxx.top:17448
> > nacos.config.enabled=true
> > nacos.config.namespace=3697a1c2-3bd2-4802-bbab-50ddaf3eaa6f
> > > > > @Logicf 下周修复
> > > > 
> > > > 
> > > > 这个问题在修复么， 现在出现的机率非常高，影响使用。
> > > 
> > > 
> > > 方便告知下application.properties有关nacos是如何配置的吗
> 
> 目前我这里没有复现出错误，所以能不能麻烦你在出现此问题时，调试到com.alibaba.nacos.spring.context.event下的DeferredApplicationEventPublisher对象，查看List deferredEvents列表中的内容并截图下？

好的， 3q

**Comment by chuntaojun** [comment]
> > > # Nacos discovery
> > > nacos.discovery.server-addr=gm.xxx.top:17448
> > > nacos.discovery.namespace=3697a1c2-3bd2-4802-bbab-50ddaf3eaa6f
> > > # Nacos config
> > > nacos.config.serverAddr=gm.xxx.top:17448
> > > nacos.config.enabled=true
> > > nacos.config.namespace=3697a1c2-3bd2-4802-bbab-50ddaf3eaa6f
> > > > > > @Logicf 下周修复
> > > > > 
> > > > > 
> > > > > 这个问题在修复么， 现在出现的机率非常高，影响使用。
> > > > 
> > > > 
> > > > 方便告知下application.properties有关nacos是如何配置的吗
> > 
> > 
> > 目前我这里没有复现出错误，所以能不能麻烦你在出现此问题时，调试到com.alibaba.nacos.spring.context.event下的DeferredApplicationEventPublisher对象，查看List deferredEvents列表中的内容并截图下？
> 
> 好的， 3q

如果你方便的话，可以加我钉钉 `dvxx6ro`

**Comment by Logicf** [comment]
bug 参考信息补充
![image](https://user-images.githubusercontent.com/23493090/58623872-828d1200-8301-11e9-964b-5c6989871a4a.png)
![image](https://user-images.githubusercontent.com/23493090/58623892-8ae54d00-8301-11e9-9490-1094de858462.png)
线程堆栈信息
[Full Thread Dump.txt](https://github.com/nacos-group/nacos-spring-project/files/3236391/Full.Thread.Dump.txt)
每次启动前重新发布下有关配置 然后 工程内各个配置 参照如下试试 可以提高 触发概率
并且按如下配置引入 可提高bug触发率
![image](https://user-images.githubusercontent.com/23493090/58624058-ed3e4d80-8301-11e9-8908-72cb1104085e.png)

**Comment by chuntaojun** [comment]
> bug 参考信息补充
> ![image](https://user-images.githubusercontent.com/23493090/58623872-828d1200-8301-11e9-964b-5c6989871a4a.png)
> ![image](https://user-images.githubusercontent.com/23493090/58623892-8ae54d00-8301-11e9-9490-1094de858462.png)
> 线程堆栈信息
> [Full Thread Dump.txt](https://github.com/nacos-group/nacos-spring-project/files/3236391/Full.Thread.Dump.txt)
> 每次启动前重新发布下有关配置 然后 工程内各个配置 参照如下试试 可以提高 触发概率
> 并且按如下配置引入 可提高bug触发率
> ![image](https://user-images.githubusercontent.com/23493090/58624058-ed3e4d80-8301-11e9-8908-72cb1104085e.png)

该错误已解决，看看pr何时merge，你可以看看这里：[nacos-springboot-NPE](https://github.com/nacos-group/nacos-spring-boot-project/issues/21)

**Comment by chuntaojun** [comment]
#94
