### ISSUE TITLE
Spring boot应用启动被终止

### ISSUE THREAD

**Issue by Logicf** [nacos-group/nacos-spring-project#86]
nacos-client 1.0.0

具体异常日志如下
java.lang.NullPointerException：
java.util.LinkedList $ ListItr.next（LinkedList.java:893）〜[na：1.8.0_202] 
at com.alibaba.nacos.spring.context.event.DeferredApplicationEventPublisher .replayDeferredEvents（DeferredApplicationEventPublisher.java:75）〜[nacos-spring-context-0.2.2-RC1.jar：na] 
at com.alibaba.nacos.spring.context.event.DeferredApplicationEventPublisher.onApplicationEvent（DeferredApplicationEventPublisher.java:69） 〜[nacos-spring-context-0.2.2-RC1.jar：na] 
at com.alibaba.nacos.spring.context.event.DeferredApplicationEventPublisher.onApplicationEvent（DeferredApplicationEventPublisher.java:37）〜[nacos-spring-context-0.2 0.2-RC1.jar：NA]
org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener（SimpleApplicationEventMulticaster.java:172）〜[spring-context-5.1.3.RELEASE.jar：5.1.3.RELEASE] 
org.springframework.context.event.SimpleApplicationEventMulticaster。 org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent（SimpleApplicationEventMulticaster.java:139）〜[spring] 
中的invokeListener（SimpleApplicationEventMulticaster.java:165）〜[spring-context-5.1.3.RELEASE.jar：5.1.3.RELEASE] -context-5.1.3.RELEASE.jar：5.1.3.RELEASE] 
at org.springframework.context.support.AbstractApplicationContext.publishEvent（AbstractApplicationContext.java:398）〜[spring-context-5.1.3.RELEASE.jar： 5.1.3.RELEASE]
org.springframework.context.support.AbstractApplicationContext.publishEvent（AbstractApplicationContext.java:355）〜[spring-context-5.1.3.RELEASE.jar：5.1.3.RELEASE] 
org.springframework.context.support.AbstractApplicationContext。
在org.springframework.context.support.AbstractApplicationContext.refresh（AbstractApplicationContext.java:549）〜[spring ]的finishRefresh（AbstractApplicationContext.java:882）〜[spring-context-5.1.3.RELEASE.jar：5.1.3.RELEASE] -context-5.1.3.RELEASE.jar：5.1.3.RELEASE] 
在org.springframework.boot.SpringApplication.refresh（SpringApplication.java:775）〜[spring-boot-2.1.1.RELEASE.jar：2.1。 1.RELEASE] 
org.springframework.boot.SpringApplication.refreshContext（SpringApplication.java:397）〜[spring-boot-2.1.1.RELEASE.jar：2.1.1.RELEASE]
at org.springframework.boot.SpringApplication.run（SpringApplication.java:316）〜[spring-boot-2.1.1.RELEASE.jar：2.1.1.RELEASE] 
at com.vandream.erp.account.AccountServiceApplication.main（ AccountServiceApplication.java:86）[classes /：na]

**Comment by nkorange** [comment]
Will fix in #85
